### ISSUE TITLE
Too few arguments to function email_confirm_user_presave()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/email_confirm#1]
The hook is just passing `$account` now, not what's there.

This could mean rethinking the whole approach in this function since it's changing the form state that's getting saved.

**Comment by izmeez** [comment]
Just installed this module and seeing the same error with a warning (on php 8.1.17):

`Warning: email_confirm_user_presave(): Argument #1 ($edit) must be passed by reference, value given in module_invoke_all() (line 975 of .../core/includes/module.inc).

ArgumentCountError: Too few arguments to function email_confirm_user_presave(), 1 passed in .../core/includes/module.inc on line 975 and exactly 3 expected in email_confirm_user_presave() (line 157 of .../modules/email_confirm/email_confirm.module).`

**Comment by izmeez** [comment]
This issue is actually critical in that it blocks "Manage user accounts" preventing changes from being saved until the email_confirm module is disabled.

**Comment by sdubois** [comment]
I am also encountering this error. I am using email_confirm in conjuction with passwordless, but I am not sure if that is part of the problem. This is a critical error.

**Comment by herbdool** [comment]
I have no idea why I made a release of this module 2 years ago. It clearly was not fully ported yet. I haven't used the module so I can see why it didn't come up.

I've got a PR to fix that.

**Comment by izmeez** [comment]
Thanks very much, it seems to be working now although I haven't fully tested it I haven't encountered blocking errors.

I, for one, am glad you decided to release this module, I think it is one of the must have modules for any serious user login site.

> I have no idea why I made a release of this module 2 years ago. It clearly was not fully ported yet. I haven't used the module so I can see why it didn't come up.
> 
> I've got a PR to fix that.
